"""Native-log false-green and waiver contracts, gated by valid controls."""

import json
from pathlib import Path
import sys

import pytest
import yaml

from test_end_to_end import load_script, portable_parser
from common.acs_test_framework_runner.qa_evidence import run_command


CONTRACTS = yaml.safe_load(Path(__file__).with_name("native_contracts.yaml").read_text())
NATIVE = [{**case, "mode": mode} for case in CONTRACTS["native"] for mode in case["modes"]]
NEGATIVE = [(case, variant) for case in NATIVE for variant in case["negatives"]]


def native_log(case, variant="positive", failed=0):
    family, suite = case["format"], case["suite"]
    if variant == "empty":
        return ""
    if family == "bsa":
        header = f" {suite} Architecture Compliance Suite\n          Version 1.2.1\n"
        prefix = "B" if suite == "BSA" else "S"
        return header if variant == "header" else (
            header + "\n    *** Running PE tests ***\n\n"
            f"{prefix}_PE_01 : 1 : Native architecture check\nResult: PASSED\n"
            "---------- ACS Summary ----------\nTotal Rules Run : 1\nPassed : 1\nFailed : 0\n"
            f"*** {suite} tests complete. Reset the system. ***\n")
    if family == "fwts":
        header = "Results generated by fwts: Version V26.01.00.\n"
        if variant == "header":
            return header
        group = case["group"]
        assertions = "".join(f"{'FAILED' if failed else 'PASSED'}: Test 1, native assertion {i + 1}.\n"
                             for i in range(failed or 1))
        return (header + f"Running tests: {group}\n" + "-" * 80
                + f"\n{group}: Native firmware check.\n" + "-" * 80
                + "\nTest 1 of 1: Native firmware check.\n" + assertions + "\n" + "=" * 80
                + f"\n{int(not failed)} passed, {failed} failed, 0 warning, 0 aborted, 0 skipped, 0 info only.\n"
                + "=" * 80 + "\n")
    if family == "sct":
        if variant == "header":
            return "BBR ACS 2.1.1 (SBBR)\n"
        text = ""
        status = "FAIL" if variant == "parent_failure" else "PASS"
        for i, name in enumerate(case["entries"], 1):
            guid = f"00000000-0000-4000-8000-{i:012d}"
            text += (f"BBR ACS 2.1.1 (SBBR)\n{name}\nRevision 0x00010001\n"
                     f"Test Entry Point GUID: {guid}\nTest Configuration #0\n"
                     "Native SCT check\nTest Started: 09/17/26 05:55a\n")
            if variant != "parent_failure":
                text += f"Native check {i} -- PASS\n{guid}\n/native/Test.c:{i}:native passed result\n"
            text += f"\nReturned Status Code: 0x00000000\n{name}: [{status}]\n"
        return text
    if family == "robot":
        status = "UNKNOWN" if variant == "unknown_status" else "PASS"
        terminal = "" if variant == "missing_status" else f'<status status="{status}"/>'
        return ('<robot><suite name="SBMR-ACS"><suite name="Host">'
                f'<test name="Native command">{terminal}</test></suite></suite></robot>')
    if family == "tpm":
        return "Capture ended before TPM results\n" if variant == "header" else "Verify native TPM measurement : PASS\n"
    if family == "capsule":
        text = "Testing ESRT FW version update\nINFO: Native ESRT check\n"
        return text if variant == "missing_completion" else text + "RESULTS: Overall Capsule Update Result: PASSED\n"
    raise AssertionError(f"Unknown native fixture format: {family}")


@pytest.fixture(scope="module")
def native_context(portable_parser, tmp_path_factory):
    return {"parser": portable_parser, "root": tmp_path_factory.mktemp("native-contracts"), "controls": {},
            "validator": load_script(portable_parser / "validate.py", "native_artifact_validator"),
            "registry": {item["canonical"]: item for item in json.loads(
                (portable_parser / "suite_registry.json").read_text())["suites"]}}


def invoke(context, case, name, text, waiver=None):
    folder = context["root"] / case["mode"] / case["suite"] / name
    source = folder / "input/acs_results" / case["relative"]
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_text(text)
    band = "SystemReady Devicetree band" if case["mode"] == "DT" else "SystemReady band"
    config = folder / "acs_config.txt"
    config.write_text("ACS version: Native QA\nSRS version: SRS 3.1.1\nBSA version: BSA v1.2\n"
                      "SBSA version: SBSA v8.0\nSBBR version: BBR v2.1\nEBBR version: EBBR v2.2.0\n"
                      "BBSR version: BBSR v1.3\nSBMR version: SBMR v2.1\n"
                      f"Device Tree Version: v0.4\nBand: {band}\n")
    system = folder / "system_config.txt"
    system.write_text("FW source code: Native QA fixture\n")
    output = folder / "output"
    command = [sys.executable, context["parser"] / "standalone_runner.py", "--mode", case["mode"],
               "--suite", case["suite"], "--input-log", folder / "input/acs_results",
               "--output", output, "--outputs", "summary", "--acs-config", config, "--system-config", system]
    if case.get("category"):
        category = folder / "category.json"
        category.write_text(json.dumps(case["category"]))
        command.extend(["--test-category", category])
    if waiver is not None:
        path = folder / "waiver.json"
        path.write_text(json.dumps(waiver))
        command.extend(["--waiver", path])
    result = run_command(command, cwd=folder, evidence_dir=folder, name="parser")
    observation = {"exit": result.returncode, "folder": folder, "output": output,
                   "evidence": [folder / "parser.command.json", folder / "parser.log", source],
                   "traceback": "Traceback (most recent call last)" in result.stdout}
    registration = context["registry"][case["suite"]]
    raw_path = output / "acs_jsons" / registration["json_output"]
    merged_path = output / "acs_jsons/merged_results.json"
    if not raw_path.is_file() or not merged_path.is_file():
        return observation
    raw = json.loads(raw_path.read_text())
    merged = json.loads(merged_path.read_text())
    label = (("EBBR-" if case["mode"] == "DT" else "SBBR-") + case["suite"]
             if case["suite"] in ("FWTS", "SCT") else registration["requirement_key"])
    summary = merged["Suite_Name: acs_info"]["ACS Results Summary"]
    observation.update(raw=raw, counts=context["validator"]._summary_values(raw["suite_summary"]),
                       records=context["validator"]._leaf_result_records(raw, registration["json_to_html"]),
                       suite_status=[value for key, value in summary.items()
                                     if key.rsplit(":", 1)[-1].strip() == label + "_compliance"])
    observation["evidence"].extend([raw_path, merged_path])
    html_counts = []
    for filename in (registration["detailed_html"], registration["summary_html"]):
        path = output / "html_detailed_summaries" / filename
        if path.is_file():
            document = context["validator"]._read_html(path)
            html_counts.extend(context["validator"]._summary_maps(document, path))
            if filename == registration["detailed_html"]:
                observation["html_records"], _ = context["validator"]._detail_records(document, path)
            observation["evidence"].append(path)
    observation["html_counts"] = html_counts
    return observation


def check(qa, actual, expected, case, observation, issue, stage, status="FAIL"):
    qa.check(actual, expected, issue_id=issue, suite=case["suite"], mode=case["mode"],
             stage=stage, status=status, evidence=observation["evidence"])


def assert_counts(qa, observation, expected, case, issue, stage, status="FAIL"):
    check(qa, observation["exit"], 0, case, observation, issue, stage, status)
    counts = observation.get("counts", {})
    check(qa, {key: counts.get(key, 0) for key in expected}, expected,
          case, observation, issue, stage, status)
    check(qa, {key: value for key, value in counts.items() if key != "total" and value},
          {key: value for key, value in expected.items() if value},
          case, observation, issue, stage, status)
    if "total" in counts:
        check(qa, counts["total"], sum(expected.values()), case, observation, issue, stage, status)
    html = observation.get("html_counts", [])
    check(qa, len(html), 2, case, observation, issue, stage, status)
    for summary in html:
        check(qa, {key: summary.get(key, 0) for key in expected}, expected,
              case, observation, issue, stage, status)
        check(qa, {key: value for key, value in summary.items() if key != "total" and value},
              {key: value for key, value in expected.items() if value},
              case, observation, issue, stage, status)
        check(qa, summary.get("total"), sum(expected.values()), case, observation, issue, stage, status)


def assert_records(qa, observation, expected, case, issue, stage, status="FAIL"):
    for field in ("records", "html_records"):
        actual = sorted([list(record) for record in observation.get(field, [])])
        check(qa, actual, sorted(expected), case, observation, issue, stage, status)


def positive_control(context, qa, case):
    key = (case["suite"], case["mode"])
    if key not in context["controls"]:
        context["controls"][key] = invoke(context, case, "positive", native_log(case))
    observation = context["controls"][key]
    assert_counts(qa, observation, {"passed": case["passed"], "failed": 0, "failed_with_waiver": 0},
                  case, "NATIVE_POSITIVE_CONTROL", "positive-control", "BLOCKED")
    check(qa, observation.get("suite_status"), ["Compliant"], case, observation,
          "NATIVE_POSITIVE_CONTROL", "positive-control", "BLOCKED")
    assert_records(qa, observation, case["records"], case,
                   "NATIVE_POSITIVE_CONTROL", "positive-control-identity", "BLOCKED")
    return observation


@pytest.mark.parametrize("case", NATIVE, ids=lambda case: case["suite"] + "-" + case["mode"])
def test_native_positive_control(native_context, qa, case):
    positive_control(native_context, qa, case)


@pytest.mark.parametrize("case,variant", NEGATIVE,
                         ids=[case["suite"] + "-" + case["mode"] + "-" + variant for case, variant in NEGATIVE])
def test_native_incomplete_evidence_cannot_be_green(native_context, qa, case, variant):
    positive_control(native_context, qa, case)
    observation = invoke(native_context, case, variant, native_log(case, variant))
    issue = "NATIVE_" + variant.upper()
    check(qa, observation["exit"] in (0, 5), True, case, observation, issue, "native-input")
    check(qa, observation["traceback"], False, case, observation, issue, "native-input")
    if observation["exit"] == 5 and variant != "parent_failure":
        check(qa, observation["output"].exists(), False, case, observation, issue, "failure-cleanup")
        return
    if variant == "parent_failure":
        assert_counts(qa, observation, {"passed": 0, "failed": 2, "failed_with_waiver": 0},
                      case, issue, "log-json-html-counts")
        entries = observation["raw"]["test_results"]
        check(qa, [(entry.get("Test_case"), entry.get("test_result")) for entry in entries],
              [(name, "FAILED") for name in case["entries"]], case, observation, issue, "log-json-identity")
    else:
        check(qa, observation.get("counts", {}).get("passed"), 0,
              case, observation, issue, "no-invented-pass")
        check(qa, len(observation.get("html_counts", [])), 2,
              case, observation, issue, "html-summary-presence")
        for summary in observation["html_counts"]:
            check(qa, summary.get("passed", 0), 0, case, observation, issue, "html-no-invented-pass")
    statuses = observation.get("suite_status", [])
    check(qa, len(statuses), 1, case, observation, issue, "merged-compliance")
    if not statuses[0].strip().lower().startswith(("not compliant", "not run")):
        check(qa, statuses[0], "Not Compliant or Not Run", case, observation, issue, "merged-compliance")


def whole_suite_waiver(name):
    return {"Suites": [{"Suite": name, "Reason": "Approved native QA waiver"}]}


def matched_device_waiver(description):
    return {"Suites": [{"Suite": "Standalone", "TestSuites": [{"TestCase": {"SubTests": [
        {"sub_Test_Description": description, "Reason": "Approved native QA waiver"}]}}]}]}


@pytest.mark.parametrize("scenario", ["fwts_two_assertions", "passed_match", "runtime", "unmatched", "idempotence"])
def test_native_waiver_contracts(native_context, qa, scenario):
    key = "fwts" if scenario in ("fwts_two_assertions", "idempotence") else "runtime" if scenario == "runtime" else "kselftest"
    case = CONTRACTS["waivers"][key]
    failed = 2 if scenario == "fwts_two_assertions" else 1 if key != "kselftest" else 0
    text = native_log(case, failed=failed) if key == "fwts" else case["text"]
    before = invoke(native_context, case, scenario + "-control", text)
    expected_before = {"passed": int(not failed), "failed": failed, "failed_with_waiver": 0}
    assert_counts(qa, before, expected_before, case, "WAIVER_CONTROL", "unwaived-control", "BLOCKED")
    assert_records(qa, before, case["records"], case, "WAIVER_CONTROL", "unwaived-control-identity", "BLOCKED")
    waiver = (matched_device_waiver("Native passing device check" if scenario == "passed_match" else "Not present in this log")
              if key == "kselftest" else whole_suite_waiver("FWTS" if key == "fwts" else "Standalone"))
    after = invoke(native_context, case, scenario, text, waiver)
    expected_after = {"passed": int(not failed), "failed": 0, "failed_with_waiver": failed}
    status = "BLOCKED" if scenario == "idempotence" else "FAIL"
    assert_counts(qa, after, expected_after, case, "WAIVER_" + scenario.upper(), "waiver-json-html", status)
    expected_records = [[identity, description, "failed_with_waiver" if value == "failed" else value]
                        for identity, description, value in case["records"]]
    assert_records(qa, after, expected_records, case, "WAIVER_" + scenario.upper(), "waived-result-identity", status)
    if key == "kselftest":
        check(qa, after["raw"]["test_results"][0]["subtests"], before["raw"]["test_results"][0]["subtests"],
              case, after, "WAIVER_" + scenario.upper(), "unchanged-passed-results")
    if scenario == "idempotence":
        folder = after["folder"] / "second-application"
        folder.mkdir()
        raw = folder / "fwts.json"
        raw.write_text(json.dumps(after["raw"]))
        result = run_command([sys.executable, native_context["parser"] / "apply_waivers.py", "FWTS", raw,
                              after["folder"] / "waiver.json", native_context["parser"] / "test_categoryDT.json", "--quiet"],
                             cwd=folder, evidence_dir=folder, name="parser")
        after["evidence"].extend([raw, folder / "parser.command.json", folder / "parser.log"])
        check(qa, result.returncode, 0, case, after, "WAIVER_IDEMPOTENCE", "second-application")
        check(qa, json.loads(raw.read_text()), after["raw"], case, after, "WAIVER_IDEMPOTENCE", "second-application")
    compliance = f"Compliant with waivers: Waivers {failed}" if failed else "Compliant"
    check(qa, after.get("suite_status"), [compliance], case, after,
          "WAIVER_SUITE_COMPLIANCE", "merged-compliance")


def test_whole_parent_bsa_waiver_preserves_passed_descendants(native_context, qa):
    case = CONTRACTS["waivers"]["bsa"]
    before = invoke(native_context, case, "parent-control", case["text"])
    assert_counts(qa, before, {"passed": 0, "failed": 1, "failed_with_waiver": 0},
                  case, "BSA_PARENT_WAIVER_CONTROL", "unwaived-control", "BLOCKED")
    assert_records(qa, before, case["records"], case, "BSA_PARENT_WAIVER_CONTROL", "unwaived-control-identity", "BLOCKED")
    waiver = {"Suites": [{"Suite": "BSA", "TestSuites": [{"TestSuite": "PE", "TestCases": [{
        "Test_case": "B_PE_01 : 1", "Reason": "Approved whole-parent waiver",
        "SubTests": [{"sub_Rule_ID": "B_CHILD_01", "Reason": "Approved child waiver"}],
    }]}]}]}
    after = invoke(native_context, case, "parent-waiver", case["text"], waiver)
    assert_counts(qa, after, {"passed": 0, "failed": 0, "failed_with_waiver": 1},
                  case, "BSA_WHOLE_PARENT_WAIVER", "waiver-json-html")
    expected_records = [[identity, description, "failed_with_waiver" if value == "failed" else value]
                        for identity, description, value in case["records"]]
    assert_records(qa, after, expected_records, case, "BSA_WHOLE_PARENT_WAIVER", "waived-result-identity")
    check(qa, after.get("suite_status"), ["Compliant with waivers: Waivers 1"],
          case, after, "BSA_WHOLE_PARENT_WAIVER", "merged-compliance")
    parent = after["raw"]["test_results"][0]["testcases"][0]
    check(qa, parent["Test_result"], "FAILED (WITH WAIVER)", case, after, "BSA_WHOLE_PARENT_WAIVER", "parent-result")
    check(qa, [child["sub_test_result"] for child in parent["subtests"]],
          ["FAILED (WITH WAIVER)", "FAILED (WITH WAIVER)", "PASSED"],
          case, after, "BSA_WHOLE_PARENT_WAIVER", "descendant-results")
